wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: Net
dataset:
  desc: null
  value: Custom
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728300594.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.16
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
